app = "koraforms"
primary_region = "iad"

[build]

[env]
  PORT = "3001"
  NODE_ENV = "production"
  DB_PATH = "/data/koraforms-server.db"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[mounts]
  source = "koraforms_data"
  destination = "/data"
